---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-asan:
    platforms:
      - Linux64 ASan
    types:
      opt:
        task: tasks/builds/opt_linux64_asan.yml
      debug:
        task: tasks/builds/dbg_linux64_asan.yml
  linux64-pgo:
    platforms:
      - Linux64 PGO
    types:
      opt:
        task: tasks/builds/opt_linux64_pgo.yml
