# This is the "base" task which contains the common values all builds must
# provide.
---
taskId: {{build_slugid}}
docker-image: phone-builder
task:
  created:
    relative-datestamp: '0 seconds'
  deadline:
    relative-datestamp: '24 hours'
  metadata:
    source: '{{source}}'
    owner: mozilla-taskcluster-maintenance@mozilla.com

  tags:
    createdForUser: {{owner}}

  workerType: b2gbuild
  provisionerId: aws-provisioner-v1
  schedulerId: task-graph-scheduler

  routes:
    - 'index.gecko.v1.{{project}}.revision.linux.{{head_rev}}.{{build_name}}.{{build_type}}'
    - 'index.gecko.v1.{{project}}.latest.linux.{{build_name}}.{{build_type}}'

  scopes:
    # Nearly all of our build tasks use tc-vcs so just include the scope across
    # the board.
    - 'docker-worker:cache:level-{{level}}-{{project}}-tc-vcs'

  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId:
        task-reference: "<docker-image>"

    # One hour is a good value for most builds
    maxRunTime: 3600

    cache:
      level-{{level}}-{{project}}-tc-vcs: '/home/worker/.tc-vcs'

    # All builds share a common artifact directory for ease of uploading.
    artifacts:
      'private/build':
        type: directory
        path: '/home/worker/artifacts/'
        expires:
          relative-datestamp: '1 year'
      'public/build':
        type: directory
        path: '/home/worker/artifacts-public/'
        expires:
          relative-datestamp: '1 year'


    env:
      # Common environment variables for checking out gecko
      MOZ_BUILD_DATE: '{{pushdate}}'
      GECKO_BASE_REPOSITORY: '{{base_repository}}'
      GECKO_HEAD_REPOSITORY: '{{head_repository}}'
      GECKO_HEAD_REV: '{{head_rev}}'
      GECKO_HEAD_REF: '{{head_ref}}'

  extra:
    build_product: 'b2g'
    build_name: '{{build_name}}'
    build_type: '{{build_type}}'
    index:
      rank: {{rank}}
    treeherder:
      jobKind: build
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
