[package]
name = "webrender_bindings"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"

[dependencies]
rayon = "0.8"
thread_profiler = "0.1.1"
euclid = "0.15"
app_units = "0.5.6"
gleam = "0.4.14"
log = "0.3"

[dependencies.webrender]
path = "../webrender"
version = "0.54.0"
default-features = false

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.4"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.4"
core-graphics = "0.12.3"
foreign-types = "0.3.0"

