[package]
name = "webrender_bindings"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"

[dependencies]
webrender_traits = {path = "../webrender_traits", version = "0.19"}
euclid = "0.11"
app_units = "0.4"
gleam = "0.2"
fnv="1.0"

[dependencies.webrender]
path = "../webrender"
version = "0.19"
default-features = false
features = ["codegen"]

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.2.2"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2.8"
