[package]
name = "webrender_bindings"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"

[dependencies]
rayon = "0.8"
thread_profiler = "0.1.1"
euclid = "0.16"
app_units = "0.6"
gleam = "0.4.20"
log = "0.3"

[dependencies.webrender]
path = "../webrender"
version = "0.57.0"
default-features = false
features = ["capture"]

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.5"
core-graphics = "0.13"
foreign-types = "0.3.0"

