---

# The order of the main categories are defined in index.rst
# Sub categories orders are preserved
categories:
    source_doc:
        - browser
        - dom
        - gfx
        - toolkit
        - dom/bindings/webidl
        - modules/libpref
        - remote
        - services/common/services
        - uriloader
        - js
    build_doc:
        - mach
        - tools/try
        - build/buildsystem
        - taskcluster
        - tools/docs
    testing_doc:
        - testing/marionette
        - testing/geckodriver
    code_quality_doc:
        - tools/lint
    l10n_doc:
        - intl
        - tools/compare-locales
    python_doc:
        - mozbase
        - python
    fennec_doc:
        - mobile/android

redirects:
    browser/browser: browser
    dom/dom: dom
    gfx/gfx: gfx
    modules/libpref/libpref: modules/libpref
    python/mach: mach
    python/python: python
    taskcluster/taskcluster: taskcluster
    testing/geckodriver/geckodriver: testing/geckodriver
    testing/marionette/marionette: testing/marionette
    toolkit/components/telemetry/telemetry: toolkit/components/telemetry
