[package]

name = "servo"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
build = "build.rs"
publish = false

[[bin]]
name = "servo"
path = "main.rs"
test = false
bench = false

[dev-dependencies]
deny_public_fields_tests = {path = "../../tests/unit/deny_public_fields"}
gfx_tests = {path = "../../tests/unit/gfx"}
layout_tests = {path = "../../tests/unit/layout"}
malloc_size_of_tests = {path = "../../tests/unit/malloc_size_of"}
metrics_tests = {path = "../../tests/unit/metrics"}
msg_tests = {path = "../../tests/unit/msg"}
net_tests = {path = "../../tests/unit/net"}
net_traits_tests = {path = "../../tests/unit/net_traits"}
profile_tests = {path = "../../tests/unit/profile"}
script_tests = {path = "../../tests/unit/script"}
script_plugins_tests = {path = "../../tests/unit/script_plugins"}
servo_config_tests = {path = "../../tests/unit/servo_config"}
servo_remutex_tests = {path = "../../tests/unit/servo_remutex"}
style_tests = {path = "../../tests/unit/style"}

[features]
default = ["unstable", "default-except-unstable"]
default-except-unstable = ["webdriver", "max_log_level"]
max_log_level = ["log/release_max_level_info"]
webdriver = ["libservo/webdriver"]
energy-profiling = ["libservo/energy-profiling"]
debugmozjs = ["libservo/debugmozjs"]
googlevr = ["libservo/googlevr"]
oculusvr = ["libservo/oculusvr"]
unstable = ["libservo/unstable", "profile_tests/unstable"]

[dependencies]
backtrace = "0.3"
browserhtml = {git = "https://github.com/browserhtml/browserhtml", branch = "crate"}
glutin_app = {path = "../../ports/glutin"}
log = "0.3"
libservo = {path = "../../components/servo"}

[target.'cfg(not(target_os = "android"))'.dependencies]
sig = "0.1"

[target.'cfg(target_os = "android")'.dependencies]
android_injected_glue = "0.2"
