[package]
name = "cert_storage"
version = "0.0.1"
authors = ["Dana Keeler <dkeeler@mozilla.com>", "Mark Goodwin <mgoodwin@mozilla.com"]

[dependencies]
base64 = "0.10"
nserror = { path = "../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../xpcom/rust/nsstring" }
rkv = "^0.9"
sha2 = "^0.7"
style = { path = "../../../../servo/components/style" }
time = "0.1"
xpcom = { path = "../../../../xpcom/rust/xpcom" }
