[package]
name = "cert_storage"
version = "0.0.1"
authors = ["Dana Keeler <dkeeler@mozilla.com>", "Mark Goodwin <mgoodwin@mozilla.com"]

[dependencies]
base64 = "0.10"
byteorder = "1.2.7"
crossbeam-utils = "0.6.3"
lmdb-rkv = "0.11"
log = "0.4"
moz_task = { path = "../../../../xpcom/rust/moz_task" }
nserror = { path = "../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../xpcom/rust/nsstring" }
rkv = "^0.9"
rust_cascade = "0.3.4"
sha2 = "^0.8"
storage_variant = { path = "../../../../storage/variant" }
style = { path = "../../../../servo/components/style" }
thin-vec = { version = "0.1.0", features = ["gecko-ffi"] }
time = "0.1"
xpcom = { path = "../../../../xpcom/rust/xpcom" }
