---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_jobs.yml

# Flags specific to this branch
flags:
  post-build:
    - simulator

builds:
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_eng.yml
      debug:
        task: tasks/builds/b2g_aries_debug.yml
  nexus-5l-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_5l_eng.yml
      debug:
        task: tasks/builds/b2g_nexus_5l_debug.yml

post-build:
  simulator:
    allowed_build_tasks:
      - tasks/builds/mulet_linux.yml
    task: tasks/post-builds/mulet_simulator.yml
