# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.

jobs:
    - name: nightly-desktop
      job:
          type: decision-task
          treeherder-symbol: Nd
          triggered-by: nightly
          target-tasks-method: nightly_linux
      run-on-projects:
          - mozilla-central
          - date
      when: []  # never (temporary)

    - name: nightly-android
      job:
          type: decision-task
          treeherder-symbol: Na
          triggered-by: nightly
          target-tasks-method: nightly_fennec
      run-on-projects:
          - mozilla-central
          - date
      when: []  # never (temporary)

    - name: nightly-mochitest-valgrind
      job:
          type: decision-task
          treeherder-symbol: Vg
          target-tasks-method: mochitest_valgrind
      run-on-projects:
          - mozilla-central
      when:
          - {hour: 16, minute: 0}
          - {hour: 4, minute: 0}
