# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.update_verify_config:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   name: secondary-update-verify-config
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-product: firefox
   shipping-phase: promote
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      docker-image:
         in-tree: "update-verify"
      max-run-time: 3600
      artifacts:
         - name: public/build/update-verify.cfg
           path: /builds/worker/checkouts/gecko/update-verify.cfg
           type: file
   run:
      using: run-task
      sparse-profile: update-verify
   extra:
      app-name: browser
      product: firefox
      archive-prefix:
         by-project:
            birch: "http://ftp.stage.mozaws.net/pub"
            default: "https://archive.mozilla.org/pub"
      previous-archive-prefix:
         by-project:
            birch: "https://archive.mozilla.org/pub"
            default: null
      aus-server:
         by-project:
            birch: "https://aus4.stage.mozaws.net"
            default: "https://aus5.mozilla.org"
      include-version:
         by-project:
            birch: "'^\\d+\\.\\d+(\\.\\d+)?$'"
            mozilla-release: "'^\\d+\\.\\d+(\\.\\d+)?$'"
            default: null
      last-watershed:
         by-project:
            birch: "57.0"
            mozilla-release: "57.0"
            default: null
      mar-channel-id-override:
         by-project:
            birch: "'^\\d+\\.\\d+(\\.\\d+)?$,firefox-mozilla-beta,firefox-mozilla-release'"
            mozilla-release: "'^\\d+\\.\\d+(\\.\\d+)?$,firefox-mozilla-beta,firefox-mozilla-release'"
            default: null
      channel:
         by-project:
            birch: "beta-localtest"
            mozilla-release: "beta-localtest"
            default: "default"
   notifications:
      completed:
         subject: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-release: ["log_collect"]
               default: []

      failed:
         subject: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               birch: ["release+tcstaging@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               default: []

      exception:
         subject: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               birch: ["release+tcstaging@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               default: []

jobs:
   firefox-secondary-linux:
      treeherder:
         symbol: UVCS
         platform: linux/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux
      extra:
         platform: linux-i686
         updater-platform: linux-x86_64

   firefox-secondary-linux64:
      treeherder:
         symbol: UVCS
         platform: linux64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux64
      extra:
         platform: linux-x86_64
         updater-platform: linux-x86_64

   firefox-secondary-macosx64:
      treeherder:
         symbol: UVCS
         platform: macosx64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: macosx64
      extra:
         platform: mac
         updater-platform: linux-x86_64

   firefox-secondary-win32:
      treeherder:
         symbol: UVCS
         platform: win32/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win32
      extra:
         platform: win32
         updater-platform: linux-x86_64

   firefox-secondary-win64:
      treeherder:
         symbol: UVCS
         platform: win64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win64
      extra:
         platform: win64
         updater-platform: linux-x86_64
