# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.update_verify_config:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   name: secondary-update-verify-config
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      docker-image:
         in-tree: "update-verify"
      max-run-time: 3600
      artifacts:
         - name: public/build/update-verify.cfg
           path: /builds/worker/checkouts/gecko/update-verify.cfg
           type: file
   run:
      using: run-task
      sparse-profile: update-verify
   extra:
      # other info passed in transform:
      #   to-build-number, to-version, to-app-version, to-display-version
      #   output-file, to-build-id
      app-name: browser
      # Note! This product is _not_ the same as shipping product.
      # It is set to "firefox" even for devedition.
      # stage-product maintains the firefox vs devedition distinction
      product: firefox
      archive-prefix:
         by-project:
            birch: "http://ftp.stage.mozaws.net/pub"
            jamun: "http://ftp.stage.mozaws.net/pub"
            maple: "http://ftp.stage.mozaws.net/pub"
            default: "https://archive.mozilla.org/pub"
      previous-archive-prefix:
         by-project:
            birch: "https://archive.mozilla.org/pub"
            jamun: "https://archive.mozilla.org/pub"
            maple: "https://archive.mozilla.org/pub"
            default: null
      aus-server:
         by-project:
            birch: "https://aus4.stage.mozaws.net"
            jamun: "https://aus4.stage.mozaws.net"
            maple: "https://aus4.stage.mozaws.net"
            default: "https://aus5.mozilla.org"
      repo-path:
         by-project:
            birch: projects/birch
            jamun: projects/jamun
            maple: projects/maple
            mozilla-beta: releases/mozilla-beta
            mozilla-release: releases/mozilla-release
            default: ADDME
      include-version:
         by-project:
            # The beta regexes (jamun, maple, mozilla-beta) do not match
            # point releases. In the rare event that we do ship a point
            # release to beta, we need to either:
            # 1) update these regexes to match that specific version
            # 2) pass a second include version that matches that specifivc version
            birch: "'^\\d+\\.\\d+(\\.\\d+)?$'"
            jamun: "'^(\\d+\\.\\d+(b\\d+)?)$'"
            maple: "'^(\\d+\\.\\d+(b\\d+)?)$'"
            mozilla-beta: "'^(\\d+\\.\\d+(b\\d+)?)$'"
            mozilla-release: "'^\\d+\\.\\d+(\\.\\d+)?$'"
            default: null
      last-watershed:
         by-project:
            birch: "57.0"
            jamun: "56.0b10"
            maple: "56.0b10"
            mozilla-beta: "56.0b10"
            mozilla-release: "57.0"
            mozilla-esr52: "TODO"
            default: null
      mar-channel-id-override:
         by-project:
            birch: "'^\\d+\\.\\d+(\\.\\d+)?$,firefox-mozilla-beta,firefox-mozilla-release'"
            mozilla-beta: "'^\\d+\\.\\d+(\\.\\d+)?$,firefox-mozilla-beta,firefox-mozilla-release'"
            default: null
      channel:
         by-project:
            mozilla-release: "beta-localtest"
            default: "default"
   notifications:
      completed:
         subject: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect"]
               mozilla-release: ["log_collect"]
               default: []

      failed:
         subject: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

      exception:
         subject: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

jobs:
   firefox-secondary-linux:
      shipping-product: firefox
      treeherder:
         symbol: UVCS
         platform: linux/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux
      extra:
         platform: linux-i686
         updater-platform: linux-x86_64

   firefox-secondary-linux64:
      shipping-product: firefox
      treeherder:
         symbol: UVCS
         platform: linux64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux64
      extra:
         platform: linux-x86_64
         updater-platform: linux-x86_64

   firefox-secondary-macosx64:
      shipping-product: firefox
      treeherder:
         symbol: UVCS
         platform: macosx64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: macosx64
      extra:
         platform: mac
         updater-platform: linux-x86_64

   firefox-secondary-win32:
      shipping-product: firefox
      treeherder:
         symbol: UVCS
         platform: win32/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win32
      extra:
         platform: win32
         updater-platform: linux-x86_64

   firefox-secondary-win64:
      shipping-product: firefox
      treeherder:
         symbol: UVCS
         platform: win64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win64
      extra:
         platform: win64
         updater-platform: linux-x86_64
