# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

# TODO: we probably hove some of these?
#kind-dependencies:

transforms:
    - taskgraph.transforms.update_verify:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    name: update-verify
    run-on-projects: [] # to make sure this never runs as part of CI
    worker-type: aws-provisioner-v1/gecko-{level}-b-linux
    worker:
        implementation: docker-worker
        os: linux
        docker-image:
            in-tree: "update-verify"
        max-run-time: 7200
    extra:
        product: firefox
        chunks: 12

jobs:
    firefox-linux64:
        description: linux64 update verify
        treeherder:
            symbol: UV
            platform: linux64/opt
            kind: test
            tier: 1
        attributes:
            build_platform: linux64

    firefox-linux:
        description: linux update verify
        treeherder:
            symbol: UV
            platform: linux/opt
            kind: test
            tier: 1
        attributes:
            build_platform: linux
