[package]
name = "mozurl"
version = "0.0.1"
authors = ["Nika Layzell <nika@thelayzells.com>"]

[dependencies]
url = "1.7.2"
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
xpcom = { path = "../../../xpcom/rust/xpcom" }
uuid = { version = "0.6", features = ["v4"] }
