[package]

name = "build-apk"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>", "The Servo Project Developers"]
license = "MPL-2.0"

[[bin]]
name = "build-apk"
path = "src/main.rs"
test = false
doc = false
bench = false

[dependencies]
walkdir = "1.0"
