language: python
python: 2.7

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV="{py27,pypy}-base"
  - TOXENV="{py27,pypy}-chrome"
  - TOXENV="{py27,pypy}-firefox"
  - TOXENV="{py27,pypy}-servo"

install:
  - pip install -U tox

script:
  - tox
