# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - beetmover-cdns

jobs:
   fennec:
      name: fennec-version-bump
      description: Release Promotion version bump
      worker-type: buildbot-bridge/buildbot-bridge
      run-on-projects: []
      run:
         using: buildbot
         product: fennec
         buildername: release-{branch}-fennec_version_bump
         release-promotion: true
         routes:
            - index.releases.v1.{branch}.latest.fennec.latest.version_bump
            - index.releases.v1.{branch}.{revision}.fennec.{underscore_version}.build{build_number}.version_bump
      notifications:
         completed:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"
         failed:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"
         exception:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"
