# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.reverse_chunk_deps:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - beetmover-checksums
   - beetmover-repackage
   # Fennec doesn't have beetmover-{checksums,repackage}, so
   # also depend on vanilla beetmover.
   - beetmover

job-defaults:
      name: post-beetmover-dummy
      description: Dummy task to deal with max_dependencies
      run-on-projects: []
      shipping-phase: promote
      worker-type: aws-provisioner-v1/gecko-{level}-b-linux
      worker:
         implementation: docker-worker
         os: linux
         docker-image: "ubuntu:16.10"
         max-run-time: 600
         command:
            - /bin/bash
            - -c
            - echo "Dummy task"
      index:
         type: release

jobs:
   firefox-promote:
      shipping-product: firefox

   devedition-promote:
      shipping-product: devedition

   fennec-promote:
      shipping-product: fennec
