sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev

before_install:
  - pkg-config --list-all
  - pkg-config --libs libudev
  - pkg-config --modversion libudev

install:
  - rustup install nightly
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
- |
  if [ "$TRAVIS_RUST_VERSION" == "nightly" ] ; then
    export ASAN_OPTIONS="detect_odr_violation=1:leak_check_at_exit=0:detect_leaks=0"
    export RUSTFLAGS="-Z sanitizer=address"
  fi
- |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ] ; then
    cargo fmt --all -- --check
    cargo clippy --all-targets -- -A renamed_and_removed_lints -A new-ret-no-self -D warnings
  fi
- cargo test
