# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - beetmover-cdns

job-defaults:
   description: Uptake monitoring job
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: push
   index:
      type: release
   run:
      using: buildbot
      release-promotion: true
   worker:
      properties:
         tuxedo_server_url:
            by-project:
               mozilla-beta: https://bounceradmin.mozilla.com/api
               mozilla-release: https://bounceradmin.mozilla.com/api
               maple: https://admin-bouncer-releng.stage.mozaws.net/api/
               default: http://localhost/api
   notifications:
      completed:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"
      failed:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"
      exception:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"

jobs:
   fennec:
      name: fennec_release_uptake_monitoring
      shipping-product: fennec
      run:
         product: fennec
         buildername: release-{branch}-fennec_uptake_monitoring
      routes:
         - index.releases.v1.{branch}.latest.fennec.latest.uptake_monitoring
         - index.releases.v1.{branch}.{revision}.fennec.{underscore_version}.build{build_number}.uptake_monitoring
      index:
         product: fennec
   firefox:
      name: firefox_release_uptake_monitoring
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}-firefox_uptake_monitoring
      routes:
         - index.releases.v1.{branch}.latest.firefox.latest.uptake_monitoring
         - index.releases.v1.{branch}.{revision}.firefox.{underscore_version}.build{build_number}.uptake_monitoring
      index:
         product: firefox
