# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

kind-dependencies:
   - post-balrog-dummy
   - post-beetmover-dummy
   - release-updates-builder
   - release-secondary-update-verify-config

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.update_verify:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   name: secondary-update-verify
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      implementation: docker-worker
      os: linux
      docker-image:
         in-tree: "update-verify"
      max-run-time: 7200
      retry-exit-status:
         - 255
      env:
         NO_BBCONFIG: "1"
         BUILD_TOOLS_REPO:
            by-project:
               birch: https://hg.mozilla.org/users/bhearsum_mozilla.com/tools
               default: https://hg.mozilla.org/build/tools
         CHANNEL:
            by-project:
               birch: "beta-localtest"
               mozilla-release: "beta-localtest"
               default: "default"
   extra:
      chunks: 12
   notifications:
      completed:
         subject: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect"]
               mozilla-release: ["log_collect"]
               default: []

      failed:
         subject: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               birch: ["release+tcstaging@mozilla.com"]
               default: []

      exception:
         subject: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               birch: ["release+tcstaging@mozilla.com"]
               default: []

jobs:
   firefox-secondary-linux64:
      description: linux64 secondary channel update verify
      shipping-product: firefox
      worker:
         env:
            VERIFY_CONFIG:
               by-project:
                  mozilla-release: "beta-firefox-linux64.cfg"
                  default: "none"
      treeherder:
         symbol: UVS
         platform: linux64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux64

   firefox-secondary-linux:
      description: linux secondary channel update verify
      shipping-product: firefox
      worker:
         env:
            VERIFY_CONFIG:
               by-project:
                  mozilla-release: "beta-firefox-linux.cfg"
                  default: "none"
      treeherder:
         symbol: UVS
         platform: linux/opt
         kind: test
         tier: 1
      attributes:
         build_platform: linux

   firefox-secondary-win64:
      description: win64 secondary channel update verify
      shipping-product: firefox
      worker:
         env:
            VERIFY_CONFIG:
               by-project:
                  mozilla-release: "beta-firefox-win64.cfg"
                  default: "none"
      treeherder:
         symbol: UVS
         platform: win64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win64

   firefox-secondary-win32:
      description: win32 secondary channel update verify
      shipping-product: firefox
      worker:
         env:
            VERIFY_CONFIG:
               by-project:
                  mozilla-release: "beta-firefox-win32.cfg"
                  default: "none"
      treeherder:
         symbol: UVS
         platform: win32/opt
         kind: test
         tier: 1
      attributes:
         build_platform: win32

   firefox-secondary-macosx64:
      description: macosx64 secondary channel update verify
      shipping-product: firefox
      worker:
         env:
            VERIFY_CONFIG:
               by-project:
                  mozilla-release: "beta-firefox-macosx64.cfg"
                  default: "none"
      treeherder:
         symbol: UVS
         platform: macosx64/opt
         kind: test
         tier: 1
      attributes:
         build_platform: macosx64
