# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

# No dependencies! Runs at the root of the promote phase
# kind-dependencies:

transforms:
   - taskgraph.transforms.release_updates:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   name: updates
   run-on-projects: []  # to make sure this never runs in CI
   shipping-phase: promote
   worker-type: buildbot-bridge/buildbot-bridge
   run:
      using: buildbot
   worker:
      properties:
         release_promotion: true
         platforms: "linux,linux64,macosx64,win32,win64"

jobs:
   firefox:
      description: updates builder
      shipping-product: firefox
      scopes:
         - project:releng:buildbot-bridge:builder-name:release-{project}_firefox_updates
      run:
         product: firefox
         buildername: release-{branch}-firefox_updates
      worker:
         properties:
            # fixme if this is actually used, kill otherwise
            # revision: ?
            # fixme if this is actually used - kill me otherwise
            # script_repo_revision: ?
            generate_bz2_blob:
               by-project:
                  mozilla-release: true
                  default: false
            product: firefox
            balrog_api_root:
               by-project:
                  mozilla-beta: https://aus4-admin.mozilla.org/api
                  mozilla-release: https://aus4-admin.mozilla.org/api
                  mozilla-esr52: https://aus4-admin.mozilla.org/api
                  default: https://balrog-admin.stage.mozaws.net/api
            channels:
               by-project:
                  jamun: "beta"
                  maple: "beta"
                  mozilla-beta: "beta"
                  # beta gets removed for non RCs by the
                  # release_updates transform
                  mozilla-release: "beta,release"
                  mozilla-esr52: "esr"
                  default: "default"
            repo_path:
               by-project:
                  jamun: "projects/jamun"
                  maple: "projects/maple"
                  mozilla-beta: "releases/mozilla-beta"
                  mozilla-release: "releases/mozilla-release"
                  mozilla-esr52": "releases/mozilla-esr52"
                  default: "default"

   devedition:
      description: updates builder
      shipping-product: devedition
      scopes:
         - project:releng:buildbot-bridge:builder-name:release-{project}_devedition_updates
      run:
         product: devedition
         buildername: release-{branch}-devedition_updates
      worker:
         properties:
            # fixme if this is actually used, kill otherwise
            # revision: ?
            # fixme if this is actually used - kill me otherwise
            # script_repo_revision: ?
            product: devedition
            balrog_api_root:
               by-project:
                  mozilla-beta: https://aus4-admin.mozilla.org/api
                  default: https://balrog-admin.stage.mozaws.net/api
            channels:
               by-project:
                  jamun: "aurora"
                  maple: "aurora"
                  mozilla-aurora: "aurora"
                  default: "default"
            repo_path:
               by-project:
                  jamun: "projects/jamun"
                  maple: "projects/maple"
                  mozilla-beta: "releases/mozilla-beta"
                  default: "default"
