[package]
name = "gecko-fuzz-targets"
version = "0.1.0"
authors = ["fuzzing@mozilla.com"]

[dependencies]
libc = "0.2"
tempfile = "3"
lazy_static = "1.4.0"

[dependencies.rkv]
version = "0.10.2"
features = ["with-fuzzer-no-link"]

[dependencies.lmdb-rkv]
version = "0.12.3"
features = ["with-fuzzer-no-link"]