[package]
name = "webrender_api"
version = "0.60.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
description = "Public API for WebRender"

[features]
nightly = ["euclid/unstable", "serde/unstable"]
ipc = ["ipc-channel"]
serialize = []
deserialize = []

[dependencies]
app_units = "0.7"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.2.1"
derive_more = "0.13"
ipc-channel = {version = "0.11.0", optional = true}
euclid = { version = "0.19.5", features = ["serde"] }
malloc_size_of_derive = "0.1"
serde = { version = "=1.0.80", features = ["rc"] }
serde_derive = { version = "=1.0.80", features = ["deserialize_in_place"] }
serde_bytes = "0.10"
time = "0.1"
wr_malloc_size_of = { version = "0.0.1", path = "../wr_malloc_size_of" }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"
core-graphics = "0.17.1"
