# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

# TODO: depends on:
# - balrog submission builders (dummy?)
kind-dependencies:
    # TODO: this makes us depend on beetmover for all platforms
    # does it matter?
    - post-beetmover-dummy

transforms:
    - taskgraph.transforms.release_deps:transforms
    - taskgraph.transforms.buildbot_update_verify:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    name: update-verify
    run-on-projects: [] # to make sure this never runs in CI
    shipping-phase: promote
    worker-type: buildbot-bridge/buildbot-bridge
    run:
        using: buildbot
    worker:
        properties:
            NO_BBCONFIG: "1"
    extra:
        chunks: 12

jobs:
    firefox-win64:
        description: win64 update verify
        shipping-product: firefox
        attributes:
            build_platform: win64
        run:
            product: firefox
        worker:
            properties:
                platform: win64
                CHANNEL:
                    by-project:
                        jamun: "beta-localtest"
                        maple: "beta-localtest"
                        mozilla-beta: "beta-localtest"
                        mozilla-release: "release-localtest"
                        mozilla-esr52: "esr-localtest"
                        default: "default"
                VERIFY_CONFIG:
                    by-project:
                        jamun: "beta-firefox-win64.cfg"
                        maple: "beta-firefox-win64.cfg"
                        mozilla-beta: "beta-firefox-win64.cfg"
                        mozilla-release: "release-firefox-win64.cfg"
                        mozilla-esr52: "esr-firefox-win64.cfg"
                        default: "none"
        extra:
            product: firefox

    firefox-win32:
        description: win32 update verify
        shipping-product: firefox
        attributes:
            build_platform: win32
        run:
            product: firefox
        worker:
            properties:
                platform: win32
                CHANNEL:
                    by-project:
                        jamun: "beta-localtest"
                        maple: "beta-localtest"
                        mozilla-beta: "beta-localtest"
                        mozilla-release: "release-localtest"
                        mozilla-esr52: "esr-localtest"
                        default: "default"
                VERIFY_CONFIG:
                    by-project:
                        jamun: "beta-firefox-win32.cfg"
                        maple: "beta-firefox-win32.cfg"
                        mozilla-beta: "beta-firefox-win32.cfg"
                        mozilla-release: "release-firefox-win32.cfg"
                        mozilla-esr52: "esr-firefox-win32.cfg"
                        default: "none"
        extra:
            product: firefox

    firefox-macosx64:
        description: macosx64 update verify
        shipping-product: firefox
        attributes:
            build_platform: macosx64
        run:
            product: firefox
        worker:
            properties:
                platform: macosx64
                CHANNEL:
                    by-project:
                        jamun: "beta-localtest"
                        maple: "beta-localtest"
                        mozilla-beta: "beta-localtest"
                        mozilla-release: "release-localtest"
                        mozilla-esr52: "esr-localtest"
                        default: "default"
                VERIFY_CONFIG:
                    by-project:
                        jamun: "beta-firefox-macosx64.cfg"
                        maple: "beta-firefox-macosx64.cfg"
                        mozilla-beta: "beta-firefox-macosx64.cfg"
                        mozilla-release: "release-firefox-macosx64.cfg"
                        mozilla-esr52: "esr-firefox-macosx64.cfg"
                        default: "none"
        extra:
            product: firefox
