# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

# TODO: we probably hove some of these?
#kind-dependencies:

transforms:
    - taskgraph.transforms.buildbot_update_verify:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    name: update-verify
    run-on-projects: [] # to make sure this never runs in CI
    worker-type: buildbot-bridge/buildbot-bridge
    run:
        using: buildbot
    extra:
        chunks: 12
        
jobs:
    firefox-win64:
        description: win64 update verify
        attributes:
            build_platform: win64
        run:
            product: firefox
            properties:
                platform: win64
        extra:
            product: firefox

    firefox-win32:
        description: win32 update verify
        attributes:
            build_platform: win32
        run:
            product: firefox
            properties:
                platform: win32
        extra:
            product: firefox

    firefox-macosx64:
        description: macosx64 update verify
        attributes:
            build_platform: macosx64
        run:
            product: firefox
            properties:
                platform: macosx64
        extra:
            product: firefox
