$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'aries'
    build_type: 'debug'
task:
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-debug'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-debug-objdir-gecko'
    - 'docker-worker:relengapi-proxy:tooltool.download.internal'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'
  metadata:
    name: '[TC] B2G Aries Debug'

  payload:
    cache:
      level-{{level}}-{{project}}-build-aries-debug: /home/worker/workspace
      level-{{level}}-{{project}}-build-aries-debug-objdir-gecko: /home/worker/objdir-gecko
    features:
      relengAPIProxy: true
    env:
      TARGET: 'aries'
      B2G_DEBUG: 1
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: Bd
      groupSymbol: Aries
      groupName: Aries Device Image
      machine:
        platform: b2g-device-image
      collection:
        debug: true
    locations:
      img: 'private/build/aries.zip'
