$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'nexus-5-l-eng'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-nexus-5-l-eng'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-nexus-5-l-eng-objdir-gecko'
    - 'docker-worker:relengapi-proxy:tooltool.download.internal'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'
  metadata:
    name: '[TC] B2G Nexus 5-L Eng'

  payload:
    cache:
      level-{{level}}-{{project}}-build-nexus-5-l-eng: /home/worker/object-folder
      level-{{level}}-{{project}}-build-nexus-5-l-eng-objdir-gecko: /home/worker/objdir-gecko
    features:
      relengAPIProxy: true
    env:
      TARGET: 'nexus-5-l'
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: Be
      groupSymbol: Nexus 5-L
      groupName: Nexus 5-L Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/nexus-5-l.zip'
