$inherits:
  from: 'tasks/builds/base_macosx64.yml'
  variables:
    build_name: 'macosx64'
    build_type: 'debug'
task:
  metadata:
      name: '[TC] MacOSX64 Debug'
      description: 'MacOSX64 Debug'

  workerType: dbg-macosx64

  payload:
    env:
      MH_CUSTOM_BUILD_VARIANT_CFG: 'cross-debug'
  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
      tier: 2
      collection:
        debug: true
