$inherits:
  from: 'tasks/builds/base_linux64.yml'
  variables:
    build_name: 'linux64'
    build_type: 'debug'
task:
  metadata:
      name: '[TC] Linux64 Debug'
      description: 'Linux64 Debug'

  routes:
    - 'index.buildbot.branches.{{project}}.linux64-debug'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux64-debug'

  workerType: 'gecko-{{level}}-b-linux'

  payload:
    env:
      MH_CUSTOM_BUILD_VARIANT_CFG: 'debug'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
      tier: 1
      collection:
        debug: true

