$inherits:
  from: 'tasks/builds/base_linux32.yml'
  variables:
    build_name: 'linux'
    build_type: 'debug'
task:
  metadata:
      name: '[TC] Linux32 Debug'
      description: 'Linux32 Debug'

  routes:
    - 'coalesce.v1.builds.{{project}}.dbg_linux32'

  workerType: 'gecko-{{level}}-b-linux'

  payload:
    supersederUrl: 'https://coalesce.mozilla-releng.net/v1/list/builds.{{project}}.dbg_linux32'

    env:
      MH_CUSTOM_BUILD_VARIANT_CFG: 'debug'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
      tier: 2
      collection:
        debug: true

