$inherits:
  from: 'tasks/builds/base_linux32.yml'
  variables:
    build_name: 'linux'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] Linux32 Opt'
      description: 'Linux32 Opt'

  routes:
      - 'coalesce.v1.builds.{{project}}.opt_linux32'

  workerType: 'gecko-{{level}}-b-linux'

  payload:
      supersederUrl: 'https://coalesce.mozilla-releng.net/v1/list/builds.{{project}}.opt_linux32'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
      tier: 2
