metadata:
  description: Single-sourcing all the informatin about artifacts into once place
  name: Beetmover declarative artifacts manifest
  owner: release@mozilla.com

s3_bucket_paths:
  fennec_nightly: pub/mobile/nightly/

definitions:
  platform:
    android1: # TODO: find a better name/structure here
      s3_platform: android-aarch64
      arch_platform: android-aarch64
    android2: # TODO: find a better name/structure here
      s3_platform: android-api-16
      arch_platform: android-arm
    android3: # TODO: find a better name/structure here
      s3_platform: android-x86_64
      arch_platform: android-x86_64
    android4: # TODO: find a better name/structure here
      s3_platform: android-x86
      arch_platform: android-i386 # namely the filename_platform from current beetmoverscript templates
  product:
    fennec: # these namings could vary
      product: Fennec
      marketing_product: Firefox for Android

mapping:
  target.web-platform.tests.tar.gz:
    description: "Web platform test suite"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.web-platform.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.web-platform.tests.tar.gz
    source_path: # where do we get it *from*? assumes prepending artifact prefix
      by-locale:
        default: {{ locale }}/target.web-platform.tests.tar.gz
        multi: target.web-platform.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.xpcshell.tests.tar.gz:
    description: "XPCShell test suite"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.xpcshell.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.xpcshell.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.xpcshell.tests.tar.gz
        multi: target.xpcshell.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target_info.txt:
    description: "File containing the buildID for the particular release"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}_info.txt
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}_info.txt
    source_path:
      by-locale:
        default: {{ locale }}/target_info.txt
        multi: target_info.txt
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.jsshell.zip:
    description: "TODO"
    pretty_name: jsshell-{{ arch_platform }}.zip
    checksums_path: jsshell-{{ arch_platform }}.zip
    source_path:
      by-locale:
        default: {{ locale }}/target.jsshell.zip
        multi: target.jsshell.zip
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  robocop.apk:
    description: "TODO"
    pretty_name: robocop.apk
    checksums_path: robocop.apk
    source_path:
      by-locale:
        default: {{ locale }}/robocop.apk
        multi: robocop.apk
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  mozharness.zip:
    description: "TODO"
    pretty_name: mozharness.zip
    checksums_path: mozharness.zip
    source_path:
      by-locale:
        default: {{ locale }}/mozharness.zip
        multi: mozharness.zip
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.txt:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.txt
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.txt
    source_path:
      by-locale:
        default: {{ locale }}/target.txt
        multi: target.txt
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.test_packages.json:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.test_packages.json
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.test_packages.json
    source_path:
      by-locale:
        default: {{ locale }}/target.test_packages.json
        multi: target.test_packages.json
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.awsy.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.awsy.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.awsy.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.awsy.tests.tar.gz
        multi: target.awsy.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.talos.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.talos.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.talos.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.talos.tests.tar.gz
        multi: target.talos.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.reftest.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.reftest.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.reftest.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.reftest.tests.tar.gz
        multi: target.reftest.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.mozinfo.json:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.mozinfo.json
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.mozinfo.json
    source_path:
      by-locale:
        default: {{ locale }}/target.mozinfo.json
        multi: target.mozinfo.json
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.mochitest.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.mochitest.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.mochitest.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.mochitest.tests.tar.gz
        multi: target.mochitest.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.json:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.json
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.json
    source_path:
      by-locale:
        default: {{ locale }}/target.json
        multi: target.json
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.crashreporter-symbols.zip:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.crashreporter-symbols.zip
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.crashreporter-symbols.zip
    source_path:
      by-locale:
        default: {{ locale }}/target.crashreporter-symbols.zip
        multi: target.crashreporter-symbols.zip
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.cppunittest.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.cppunittest.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.cppunittest.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.cppunittest.tests.tar.gz
        multi: target.cppunittest.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  target.common.tests.tar.gz:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.common.tests.tar.gz
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.common.tests.tar.gz
    source_path:
      by-locale:
        default: {{ locale }}/target.common.tests.tar.gz
        multi: target.common.tests.tar.gz
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
  buildhub.json:
    description: "TODO"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.buildhub.json
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.buildhub.json
    source_path:
      by-locale:
        default: {{ locale }}/buildhub.json
        multi: buildhub.json
    locale_prefix:
      by-locale:
        default: ''
        en-US: ''
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/
          - {{ upload_date }}-{{ branch }}-{{ platform }}/
        #localized: not implemented yet see bug 1459302
  target.apk:
    description: "The Fennec installer that needed to ship to Google Play"
    pretty_name: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.apk
    checksums_path: fennec-{{ version }}.{{ locale }}.{{ arch_platform }}.apk
    source_path:
      by-locale:
        default: {{ locale }}/target.apk
        multi: target.apk
    locale_prefix:
      by-locale:
        default: ''
        en-US: {{ locale }}/
    flags:
      needs-signing: True
      update_balrog_manifest: True
    destinations:
      by-locale:
        default:
          - latest-{{ branch }}-{{ platform }}/{{ locale_prefix }}
          - {{ upload_date }}-{{ branch }}-{{ platform }}/{{ locale_prefix }}
        localized:
          - latest-{{ branch }}-{{ platform }}-l10n/
          - {{ upload_date }}-{{ branch }}-{{ platform }}-l10n/
