---
s3_bucket_paths:
  by-platform:
    .*devedition.*:
      - pub/devedition/nightly
    default:
      - pub/firefox/nightly
default_locales:  # if given an empty locale, use these locales
  - en-US
tasktype_map:  # Map task reference to task type.
  checksums-signing: signing
platform_names:
  path_platform: ''
  filename_platform:
    by-platform:
      linux-nightly: 'linux-i686'
      linux64-nightly: 'linux-x86_64'
      linux64-asan-reporter-nightly: 'linux-x86_64-asan-reporter'
      macosx64-nightly: 'mac'
      win32-nightly: 'win32'
      win64-nightly: 'win64'
      win64-aarch64-nightly: 'win64-aarch64'
      win64-asan-reporter-nightly: 'win64-asan-reporter'
  stage_platform: ''

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
  from:
    - checksums-signing
  all_locales: true
  description: "TO_BE_OVERRIDDEN"
  locale_prefix: ''
  source_path_modifier: ''
  destinations:  # locale_prefix is appended
    by-locale:
      en-US:
        - latest-${branch}
        - latest-${branch}-l10n
        - ${year}/${month}/${upload_date}-${branch}
      default:
        - latest-${branch}-l10n
        - ${year}/${month}/${upload_date}-${branch}-l10n

# Configuration for individual files. Extends 'default', above.
mapping:
  target.checksums:
    <<: *default
    description: "Checksums file containing size, hash, sha algorithm and filename"
    pretty_name: firefox-${version}.${locale}.${filename_platform}.checksums
    checksums_path: firefox-${version}.${locale}.${filename_platform}.checksums
  target.checksums.asc:
    <<: *default
    description: "Detached signature for the checksums file"
    pretty_name: firefox-${version}.${locale}.${filename_platform}.checksums.asc
    checksums_path: firefox-${version}.${locale}.${filename_platform}.checksums.asc
