# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - push-apk
   - release-bouncer-aliases
   - release-version-bump

job-defaults:
   shipping-phase: ship

jobs:
   fennec:
      name: notify-release-drivers-publish
      description: Sends email to release-drivers telling release was published.
      run-on-projects: []
      shipping-product: fennec
      worker-type: aws-provisioner-v1/gecko-{level}-b-linux
      worker:
         implementation: docker-worker
         os: linux
         docker-image: "ubuntu:16.10"
         max-run-time: 600
         command:
            - /bin/bash
            - -c
            - echo "Dummy task"
      notifications:
         completed:
            subject: "{config[params][project]} {release_config[version]} build{release_config[build_number]} has been published to Google Play"
            message: "{config[params][project]} {release_config[version]} build{release_config[build_number]} has been published to Google Play"
            ids:
               by-project:
                  maple:
                     - "release-drivers-staging"
                  try:
                     #- "{task[tags][createdForUser]}"
                  default:
                     - "release-drivers"
      routes:
         - index.releases.v1.{branch}.{revision}.{product}.{underscore_version}.build{build_number}.email-{channel}
         - index.releases.v1.{branch}.latest.{product}.latest.email-{channel}
      index:
         type: release
         product: fennec
         job-name: android-api-16-opt
         channel:
            by-project:
               mozilla-beta: beta
               mozilla-release: release
               maple: maple
               default: unknown
