# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
#   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.task:transforms

# TODO: once release checksums is done
# kind-dependencies:
#    - release-checksums

job-defaults:
   name: release-binary-transparency
   description: Binary transparency to issue a certificate
   run-on-projects: []
   routes:
      - index.releases.v1.{branch}.latest.{product}.latest.binary_transparency
      - index.releases.v1.{branch}.{revision}.{product}.{underscore_version}.build{build_number}.binary_transparency
   index:
      type: release
   worker-type: scriptworker-prov-v1/dummy-worker-transpar
   worker:
      implementation: binary-transparency

jobs:
   firefox:
      shipping-product: firefox
      index:
         product: firefox
