# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

kind-dependencies:
   - beetmover-source
   - post-beetmover-checksums-dummy

transforms:
   - taskgraph.transforms.build:transforms
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.checksums:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   name: generate-checksums
   description: generates checksums
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      max-run-time: 1200
      artifacts:
         - name: public/build/SHA256SUMMARY
           path: /builds/worker/SHA256SUMMARY
           type: file
         - name: public/build/SHA256SUMS
           path: /builds/worker/SHA256SUMS
           type: file
         - name: public/build/SHA512SUMMARY
           path: /builds/worker/SHA512SUMMARY
           type: file
         - name: public/build/SHA512SUMS
           path: /builds/worker/SHA512SUMS
           type: file
   run:
      using: mozharness
      actions: [create-virtualenv collect-individual-checksums create-big-checksums create-summary]
      options:
         - "version={version}"
         - "build-number={build_number}"
      script: "mozharness/scripts/release/generate-checksums.py"
   index:
      type: release
   routes:
      - index.releases.v1.{branch}.latest.{product}.latest.checksums
      - index.releases.v1.{branch}.{revision}.{product}.{underscore_version}.build{build_number}.checksums
   attributes:
      build_platform: linux64
      build_type: opt
   treeherder:
      symbol: Rel(GenChcks)
      kind: test
      tier: 1
   notifications:
      completed:
         subject: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect"]
               mozilla-release: ["log_collect"]
               default: []

      failed:
         subject: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

      exception:
         subject: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

jobs:
   firefox:
      shipping-product: firefox
      index:
         product: firefox
      run:
         config:
            by-project:
               mozilla-release:
                  - releases/checksums_firefox.py
               mozilla-beta:
                  - releases/checksums_firefox.py
               maple:
                  - releases/dev_checksums_firefox.py
               default:
                  - releases/dev_checksums_firefox.py
      treeherder:
         platform: linux64/opt

   fennec:
      shipping-product: fennec
      index:
         product: fennec
      run:
         config:
            by-project:
               mozilla-release:
                  - releases/checksums_fennec.py
               mozilla-beta:
                  - releases/checksums_fennec.py
               maple:
                  - releases/dev_checksums_fennec.py
               default:
                  - releases/dev_checksums_fennec.py
      treeherder:
         platform: Android/opt

   devedition:
      shipping-product: devedition
      index:
         product: devedition
      run:
         config:
            by-project:
               mozilla-release:
                  - releases/checksums_devedition.py
               mozilla-beta:
                  - releases/checksums_devedition.py
               maple:
                  - releases/dev_checksums_devedition.py
               default:
                  - releases/dev_checksums_devedition.py
      treeherder:
         platform: linux64-devedition/opt
