[package]
name = "xpcom_macros"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
lazy_static = "1.0"
