# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_snap:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - build
   - l10n
only-for-build-platforms:
   - linux64/opt
   - linux64/debug
   - linux64-nightly/opt
   - linux-nightly/opt
   - linux64-devedition-nightly/opt
   - linux-devedition-nightly/opt


job-defaults:
   description: Generates snap image
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   # scopes:
   # - secrets:get:project/releng/snapcraft/firefox/edge
   treeherder:
      platform: linux64/opt
      kind: build
      tier: 3
   index:
      type: release
   routes:
      - index.releases.v1.{branch}.{revision}.{product}.{underscore_version}.build{build_number}.snap
      - index.releases.v1.{branch}.latest.{product}.latest.snap
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      implementation: docker-worker
      os: linux
      max-run-time: 7200
      docker-image: mozillareleases/firefox-snapcraft@sha256:107cc7a89d45ce6df30f44fe0dfd0b375b3ab443b75e92efc77c4f7bc5da8717
      artifacts:
         - name: public/build
           type: directory
           path: /home/worker/artifacts/
      command:
         - /bin/bash
         - -cx
         - >
           apt-get update &&
           apt-get dist-upgrade -y &&
           curl -o scripts.tar.bz2 {config_params[base_repository]}/archive/{config_params[head_rev]}.tar.bz2/taskcluster/docker/firefox-snap/ &&
           mkdir scripts &&
           tar xvfj scripts.tar.bz2 -C scripts --strip-components 4 &&
           cd scripts &&
           ./runme.sh
      env:
         VERSION: "{release_config[version]}"
         BUILD_NUMBER: "{release_config[build_number]}"
         CANDIDATES_DIR:
            by-project:
               maple:
                  https://net-mozaws-stage-delivery-archive.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
               default:
                  https://net-mozaws-prod-delivery-firefox.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
         LC_ALL: C.UTF-8
         LANG: C.UTF-8
      taskcluster-proxy: true
   notifications:
      completed:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"
      failed:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"
      exception:
         by-project:
            maple:
               - "release-drivers-staging"
            try:
            default:
               - "release-drivers"

jobs:
   firefox:
      shipping-product: firefox
      treeherder:
         symbol: Snap(BF)
      index:
         product: firefox
   devedition:
      shipping-product: devedition
      treeherder:
         symbol: Snap(BD)
      index:
         product: devedition
