# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
  - taskgraph.transforms.try_job:transforms
  - taskgraph.transforms.job:transforms
  - taskgraph.transforms.task:transforms

job-defaults:
  treeherder:
    kind: build
    platform: packages/opt
    tier: 1
  worker-type: aws-provisioner-v1/gecko-{level}-b-linux
  worker:
    max-run-time: 1800

jobs:
  deb7-python:
    description: "Python backport for Debian wheezy"
    treeherder:
      symbol: Deb7(python)
    run:
      using: debian-package
      dsc: "http://snapshot.debian.org/archive/debian/20160813T164221Z/pool/main/p/python2.7/python2.7_2.7.9-2+deb8u1.dsc"
      dsc-sha256: 274c293e7156edf59cb9f0a9d8cedcd94fa801df35adf39b8a9f3d776a250ead
      patch: python-wheezy.diff
      pre-build-command: debian/rules control-file

  deb7-cmake:
    description: "Cmake backport for Debian wheezy"
    treeherder:
      symbol: Deb7(cmake)
    run:
      using: debian-package
      dsc: "http://snapshot.debian.org/archive/debian-debug/20161204T031605Z/pool/main/c/cmake/cmake_3.7.1-1.dsc"
      dsc-sha256: 406a12c0d0a2e92d44a8d444fd1b32bcc29a8810e9631427161a7cb411f60172
      patch: cmake-wheezy.diff

  deb7-ninja:
    description: "Ninja backport for Debian wheezy"
    treeherder:
      symbol: Deb7(ninja)
    run:
      using: debian-package
      dsc: "http://snapshot.debian.org/archive/debian-debug/20160209T034956Z/pool/main/n/ninja-build/ninja-build_1.6.0-1.dsc"
      dsc-sha256: 25cd62b011d669c31bcd51d36d454dd826bc50af6a3af8d87bcab8948ec21626
      patch: ninja-wheezy.diff
