# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.bouncer_aliases:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - release-bouncer-check

job-defaults:
   description: Update bouncer aliases job
   worker-type:
      by-project:
         mozilla-beta: scriptworker-prov-v1/bouncer-v1
         mozilla-release: scriptworker-prov-v1/bouncer-v1
         default: scriptworker-prov-v1/bouncer-dev
   worker:
      implementation: bouncer-aliases
   scopes:
      by-project:
         mozilla-beta:
            - project:releng:bouncer:action:submission
            - project:releng:bouncer:server:production
         mozilla-release:
            - project:releng:bouncer:action:submission
            - project:releng:bouncer:server:production
         default:
            - project:releng:bouncer:action:submission
            - project:releng:bouncer:server:staging
   run-on-projects: []
   shipping-phase: ship

jobs:
   devedition:
      bouncer-products: ['installer', 'installer-ssl', 'stub-installer']
      shipping-product: devedition

   fennec:
      bouncer-products: ['apk']
      shipping-product: fennec

   firefox:
      bouncer-products: ['installer', 'installer-ssl', 'stub-installer']
      shipping-product: firefox
