# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.scriptworker:add_balrog_scopes
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - release-bouncer-check

job-defaults:
   run-on-projects: []
   shipping-phase: ship
   worker:
      implementation: balrog
      balrog-action: schedule

jobs:
   firefox:
      description: Schedule Firefox publishing in balrog
      name: release-firefox_schedule_publishing_in_balrog
      shipping-product: firefox
      worker:
         product: firefox
         publish-rules:
            by-project:
               maple: [32]
               birch: [145]
               jamun: [724]
               mozilla-beta: [32]
               mozilla-release: [145]
               mozilla-esr60: [806]
               default: []
      treeherder:
         platform: firefox-release/opt
         symbol: Rel(BSFx)
         tier: 1
         kind: build
   # FIXME: (Bug 1487172) This task should only run on esr60-like branches
   firefox-bz2:
      description: Schedule Firefox publishing in balrog (bz2)
      name: release-firefox_schedule_publishing_in_balrog-bz2
      shipping-product: firefox
      worker:
         product: firefox
         publish-rules:
            by-project:
               mozilla-esr60: [521]
               default: []
         blob-suffix: -bz2
      treeherder:
         platform: firefox-release/opt
         symbol: Rel(BSFx-bz2)
         tier: 1
         kind: build
   devedition:
      description: Schedule Devedition publishing in balrog
      name: release-devedition_schedule_publishing_in_balrog
      shipping-product: devedition
      worker:
         product: devedition
         publish-rules:
            by-project:
               maple: [10]
               mozilla-beta: [10]
               default: []
      treeherder:
         platform: devedition-release/opt
         symbol: Rel(BSDev)
         tier: 1
         kind: build
