[package]
name = "gkrust"
version = "0.1.0"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Rust code for libxul"

[dependencies]
mp4parse_capi = { path = "../../../media/libstagefright/binding/mp4parse_capi" }
nsstring = { path = "../../../xpcom/rust/nsstring" }

[lib]
path = "lib.rs"
crate-type = ["rlib"]
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false

# Explicitly specify what our profiles use.
[profile.dev]
opt-level = 1
# XXX: We're passing `-C debuginfo=1` to rustc to work around an llvm-dsymutil
# crash (bug 1301751), but rustc can't handle -g with that option, so
# turn off debug for now.
# This should be temporary until we upgrade to Rust 1.12.
debug = false
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = "abort"

[profile.release]
opt-level = 2
debug = false
rpath = false
lto = true
debug-assertions = false
panic = "abort"
