# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms


job-defaults:
      description: release bouncer submission job
      worker-type: buildbot-bridge/buildbot-bridge
      run-on-projects: []
      run:
         using: buildbot
         release-promotion: true
      notifications:
         completed:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"
         failed:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"
         exception:
            by-project:
               maple:
                  - "release-drivers-staging"
               try:
                  #- "{task[tags][createdForUser]}"
               default:
                  - "release-drivers"

jobs:
   fennec:
      name: fennec_release_bouncer_sub
      run:
         product: fennec
         buildername: release-{branch}-fennec_bncr_sub
         routes:
            - index.releases.v1.{branch}.latest.fennec.latest.bouncer_submitter
            - index.releases.v1.{branch}.{revision}.fennec.{underscore_version}.build{build_number}.bouncer_submitter
   firefox:
      name: firefox_release_bouncer_sub
      run:
         product: firefox
         buildername: release-{branch}-firefox_bncr_sub
         routes:
            - index.releases.v1.{branch}.latest.firefox.latest.bouncer_submitter
            - index.releases.v1.{branch}.{revision}.firefox.{underscore_version}.build{build_number}.bouncer_submitter
