# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.task:transforms

job-defaults:
   description: release bouncer submission job
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: promote
   index:
      type: release
   run:
      using: buildbot
      release-promotion: true
   notifications:
      completed:
         subject: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "COMPLETED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect"]
               mozilla-release: ["log_collect"]
               default: []

      failed:
         subject: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "FAILED: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

      exception:
         subject: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         message: "EXCEPTION: [{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]}] {task_def[metadata][name]} task"
         plugins:
            by-project:
               mozilla-beta: ["log_collect", "ses"]
               mozilla-release: ["log_collect", "ses"]
               default: ["ses"]
         emails:
            by-project:
               mozilla-beta: ["release-automation-notifications@mozilla.com"]
               mozilla-release: ["release-automation-notifications@mozilla.com"]
               try: ["{task_def[metadata][owner]}"]
               maple: ["release+tcstaging@mozilla.com"]
               default: []

jobs:
   fennec:
      name: fennec_release_bouncer_sub
      shipping-product: fennec
      run:
         product: fennec
         buildername: release-{branch}-fennec_bncr_sub
      routes:
         - index.releases.v1.{branch}.latest.fennec.latest.bouncer_submitter
         - index.releases.v1.{branch}.{revision}.fennec.{underscore_version}.build{build_number}.bouncer_submitter
      index:
         product: fennec
   firefox:
      name: firefox_release_bouncer_sub
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}_firefox_bncr_sub
      routes:
         - index.releases.v1.{branch}.latest.firefox.latest.bouncer_submitter
         - index.releases.v1.{branch}.{revision}.firefox.{underscore_version}.build{build_number}.bouncer_submitter
      index:
         product: firefox
   devedition:
      name: devedition_release_bouncer_sub
      shipping-product: devedition
      run:
         product: devedition
         buildername: release-{branch}_devedition_bncr_sub
      routes:
         - index.releases.v1.{branch}.latest.devedition.latest.bouncer_submitter
         - index.releases.v1.{branch}.{revision}.devedition.{underscore_version}.build{build_number}.bouncer_submitter
      index:
         product: devedition
